<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.daw</groupId>
  <artifactId>proyectoMavenIntegradoEnEclipseTomcat</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>

        <!--
            API de Jakarta Servlet utilizada por Tomcat 11.

            "provided" significa que necesitamos esta librería
            para COMPILAR, pero no la incluimos en el WAR porque
            Tomcat ya la proporciona durante la ejecución.
        -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.1.0</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>